import fs from "fs";
import path from "path";
import { ReportData } from "../type/reportTypes.js";

export function generateReport(data: ReportData): string {
  const lines: string[] = [];

  // Header
  lines.push(`# DEX Arbitrage Report`);
  lines.push(`\n> Generated: ${data.metadata.timestamp}`);
  lines.push(`\n---\n`);

  // Metadata
  lines.push(`## Run Configuration`);
  lines.push(`| Field | Value |`);
  lines.push(`|---|---|`);
  lines.push(`| Token In | ${data.metadata.tokenIn} |`);
  lines.push(`| Token Out | ${data.metadata.tokenOut} |`);
  lines.push(`| Router A | ${data.metadata.routerA} |`);
  lines.push(`| Router B | ${data.metadata.routerB} |`);
  lines.push(`| Chosen Direction | ${data.metadata.chosenDirection} |`);
  lines.push(`| Trade Size Range | ${data.metadata.minSize} → ${data.metadata.maxSize} (step ${data.metadata.stepSize}) |`);
  lines.push(`\n---\n`);

  // Viability summary
  lines.push(`## Viability Summary`);
  lines.push(`**Viable in ${data.viableScenariosCount} / ${data.totalScenariosCount} execution environments**\n`);

  // Break-even table
  lines.push(`## Break-even Summary`);
  if (data.scenarios.some(s => s.breakEven)) {
    lines.push(`| Slippage (bps) | Gas (gwei) | Break-even Range |`);
    lines.push(`|---|---|---|`);
    for (const scenario of data.scenarios) {
      if (scenario.breakEven) {
        lines.push(
          `| ${scenario.slippage} | ${scenario.gasGwei === 0 ? "live" : scenario.gasGwei} | ${scenario.breakEven.fromSize} → ${scenario.breakEven.toSize} |`
        );
      } else {
        lines.push(
          `| ${scenario.slippage} | ${scenario.gasGwei === 0 ? "live" : scenario.gasGwei} | No break-even found |`
        );
      }
    }
  } else {
    lines.push(`No break-even found across any scenario.`);
  }
  lines.push(`\n---\n`);

  // Per scenario results
  lines.push(`## Scenario Results`);
  for (const scenario of data.scenarios) {
    lines.push(
      `\n### Slippage: ${scenario.slippage} bps | Gas: ${scenario.gasGwei === 0 ? "live" : scenario.gasGwei + " gwei"}`
    );
    lines.push(`**Best Trade Size:** ${scenario.bestSize} | **Best Profit:** $${scenario.bestProfitUSD}`);
    lines.push(`\n| Trade Size | Profit (USD) |`);
    lines.push(`|---|---|`);
    for (const result of scenario.results) {
      const indicator = result.size === scenario.bestSize ? " ⭐" : "";
      lines.push(`| ${result.size} | $${result.profitUSD}${indicator} |`);
    }
  }

  lines.push(`\n---`);
  lines.push(`\n*Generated by DEX Arbitrage Simulator*`);

  return lines.join("\n");
}

export function saveReport(data: ReportData): string {
  const reportsDir = path.resolve("reports");

  if (!fs.existsSync(reportsDir)) {
    fs.mkdirSync(reportsDir, { recursive: true });
  }

  const timestamp = new Date()
    .toISOString()
    .replace(/[:.]/g, "-")
    .slice(0, 19);

  const filename = `report_${data.metadata.tokenIn}_${data.metadata.tokenOut}_${timestamp}.md`;
  const filepath = path.join(reportsDir, filename);
  const content = generateReport(data);

  fs.writeFileSync(filepath, content, "utf-8");

  return filepath;
}